---
config:
  layout: elk
---
flowchart TB
    orchestrator(["Orchestrator"]) --> web["Web Search()"] & n13(["reservation agent"]) & n21["RAG for hospital services"] & n10["medical RAG"]
    memory["vector DB (user history)"] --> n1(["classifier"]) & orchestrator
    n1 --> n2(["periority &amp; loyality score"])
    n14@{ label: "<span style=\"font-weight:\"><span class=\"gs_tkn\">vector DB (for available recorses)</span></span>" } --> n15(["availablity"])
    n15 --> n16["get()"] & n17["update()"] & n20["notify()"]
    n13 --> n14
    n17 --> n14
    n2 --> orchestrator & n19["handoff to human()"]

    n21@{ shape: rect}
    n10@{ shape: rect}
    n14@{ shape: rect}
    n16@{ shape: rect}
    n17@{ shape: rect}
    n20@{ shape: rect}
    n19@{ shape: rect}
     orchestrator:::indigo
     web:::teal
     n21:::teal
     n10:::teal
     memory:::teal
     n14:::teal
     n16:::teal
     n17:::teal
     n20:::teal
     n19:::teal
    classDef indigo stroke:#818cf8,fill:#eef2ff
    classDef teal stroke:#2dd4bf,fill:#f0fdfa
    style web stroke:#FFCDD2,fill:#BBDEFB
    style n13 color:#000000,fill:#eef2ff,stroke:#E1BEE7
    style n1 color:#000000,fill:#eef2ff,stroke:#E1BEE7
    style n2 color:#BBDEFB,fill:#2898e4
    style n15 color:#BBDEFB,fill:#2898e4
    style n16 stroke:#FFCDD2,fill:#BBDEFB
    style n17 stroke:#FFCDD2,fill:#BBDEFB
    style n20 stroke:#FFCDD2,fill:#BBDEFB
    style n19 stroke:#FFCDD2,fill:#BBDEFB